spring:
  profiles:
    active: prod
  application:
    admin:
      enabled: true
    name: zuul-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
    should-unregister-on-shutdown: true
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      startup: ${random.int}

zuul:
  ribbon-isolation-strategy: thread
  routes:
    auth-service:
      path: /auth-service/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: auth-service
  host:
    connect-timeout-millis: 10000

ribbon:
  eager-load:
    enabled: true

auth-service:
  ribbon:
    ReadTimeout: 6000

hystrix:
  command:
    auth-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000